# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp_user', '0002_auto_20180925_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('img', models.ImageField(upload_to='tset/%Y%m/%d', verbose_name='图片测试')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='user',
            name='head',
            field=models.ImageField(default='tset/201809/25/tx1.png', upload_to='head/%Y/%m', verbose_name='用户头像'),
        ),
    ]
