# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 07:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0002_activity_activityzone_activityzonegoods_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsgallery',
            name='goods_sku',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sp_goods.GoodsSKU', verbose_name='SKU商品'),
            preserve_default=False,
        ),
    ]
