# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-09-25 18:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sp_goods', '0003_goodsgallery_goods_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodsspu',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='商品详情'),
        ),
    ]
